### ISSUE TITLE
Veracode Github actions CI support

### ISSUE THREAD

**Issue by ddotpdot** [veracode/Veracode-Community-Projects#3]
Is there a plan to release an official github action for veracode scans?
https://github.com/marketplace?type=actions
Would be really helpful. 
something in the lines of - https://github.com/ctcampbell/veracode-ci-examples

**Comment by daan39** [comment]
Hi

**Comment by tjarrettveracode** [comment]
@ddotpdot  -- sorry I missed this note before. We have released official Github Actions for the following workflows:
* [Upload and Scan](https://github.com/marketplace/actions/veracode-upload-and-scan)
* [Pipeline Scan](https://github.com/marketplace/actions/veracode-static-analysis-pipeline-scan-and-sarif-import) - ingest pipeline scan results into the GitHub Security tab

Hope this is helpful.
