### ISSUE TITLE
Veracode CWE ID 80 on endpoint return value

### ISSUE THREAD

**Issue by DobreMihai-echo** [veracode/Veracode-Community-Projects#44]
Hello, and sorry to be a bother.
I am receiving a High Veracode vulnerability on the return from an endpoint. The endpoint is something like:

```
@POST
@Path("mydata") 
public List<MyDataObject> saveData(final List<MyObjectData> data) {
   return MyDataDAO.save(data);
 }
```

And I receive the vulnerability regardless of what I do. I tried to sanitize the incoming data, as well as the data that ia returned from the DAO. The only way I made it work is if the endpoint doesn't return any values. Does anyone have any ideea why it doesn't seem to work? Thank you in advance

**Comment by julz0815** [comment]
Hi @DobreMihai-echo, this is a list of community projects, which project are you talking about? Most probably you would need to contact the dedicated repository owner to get more information.

**Comment by DobreMihai-echo** [comment]
Thank you sonmuch for the swift response @julz0815 . That is my bad, sorry. I will close this issue then.
