### ISSUE TITLE
Veracode static intellij plugin not showing in  Tools menu, when  opened from search doesn't show result window

### ISSUE THREAD

**Issue by DineshSolanki** [veracode/Veracode-Community-Projects#45]
Downloaded plugin from here  - https://tools.veracode.com/integrations/IntelliJ/bin/IntelliJ.zip
earlier used to work but now not working in Intellij 2023.3.2

**Comment by julz0815** [comment]
Hi @DineshSolanki can you please send a mail to support@veracode.com? This project is about community driven tools for Veracode. We cannot really help you with this request here.

**Comment by DineshSolanki** [comment]
> Hi @DineshSolanki can you please send a mail to support@veracode.com? This project is about community driven tools for Veracode. We cannot really help you with this request here.

Sure, thanks
